#include <iostream>
using namespace std;

/* 
Jan 6, 2019  -  JLF

Project Euler problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.int main() {
*/


int main() {

	int sumEvens = 0;
	int f1 = 1;
	int f2 = 2;
	int f3;

	cout << "\n------------------------------------------------------\n";

	while ( f1 < 4000000 ) {
		if ( f1%2==0 ) { sumEvens = sumEvens + f1; }
		f3 = f1 + f2;
		f1 = f2;
		f2 = f3;
	} 

	cout << "\nFrom the C++ program:\n";
	cout << "the sum of even fibs was => " << sumEvens;

	cout << "\n------------------------------------------------------\n";

	return 0;
} // end of main
