#! /usr/bin/env python3

''' 
Jan 6, 2019  -  JLF

Project Euler problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.int main() {
'''

print(""); print("---------------------------------------------------------------"); print("");


f1 = 1;
f2 = 2;

sumNumbers = 0

while ( f1 < 4000000 ):
    if ( f1%2==0 ):
        sumNumbers = sumNumbers + f1
    f3 = f1 + f2
    f1 = f2
    f2 = f3

print("From the python program:")
print("The Sum of the even fibonacci numbers up to 4,000,000 is => " + str(sumNumbers) )



print(""); print("---------------------------------------------------------------"); print("");
